correção encaminhar mensagens e economia recursos
ldurans/izing.open.io pull request #192
Opened 2024-05-12 00:59 UTC by cleitonme

2024-05-12 13:20 UTC, ldurans requested changes
@cleitonme não iremos voltar o bull para fazer gestão das mensagens a serem enviadas. Vamos manter o envio direto ou implementar um consumer com rabbitmq.

2024-05-12 13:20 UTC, ldurans commented on backend/src/libs/wbot.ts
> +const checkMessages = async (wbot: Session, tenantId: number | string) => {
@cleitonme não iremos voltar o bull para fazer gestão das mensagens a serem enviadas. Vamos manter o envio direto ou implementar um consumer com rabbitmq.

2024-05-12 13:20 UTC, ldurans commented on backend/src/libs/wbot.ts
> +  "--disable-site-isolation-trials",
Para agilizar, desmembre a alteração dos minimal_args  em um PR para mesclarmos, por favor!

2024-05-13 20:27 UTC, closed without merging

2024-05-13 20:27 UTC, cleitonme commented
não sou bom codigos, analiso funções de outros sistemas, chatgpt e vou tentando..