Add Mensagem de Saudação e Despedida do atendimento
ldurans/izing.open.io pull request #98
Opened 2022-12-24 04:53 UTC by maxivane

Adicionei suporte a Envio de Mensagem de Saudação e de Despedida do atendimento Adicionei mais variáveis no mustache e renomiei as que tinha.
Variáveis: {{nomecontato}}  {{nomeatendente}}  {{atendimentonumero}}  {{saudacao}}

2022-12-25 23:54 UTC, patronotech commented
Muito obrigado pelo apoio e contribuição.

2022-12-26 20:40 UTC, ldurans commented
[maxivane](https://github.com/maxivane), boa tarde!

Favor verificar os seguintes pontos:

- [ ]  Extensão do comportamento para os demais canais da ferramenta. 
- [ ]  Tratamento para grupos.

Parabéns pela iniciativa, ficou realmente bom!

2022-12-26 20:43 UTC, ldurans requested changes
[maxivane](https://github.com/maxivane), boa tarde!

Favor verificar os seguintes pontos:

- Extensão do comportamento para os demais canais da ferramenta.
- Tratamento para grupos.

Parabéns pela iniciativa, ficou realmente bom!

2023-01-02 21:35 UTC, ldurans approved these changes
Aprovado para futuro ajuste da rotina nos demais canais.

2023-01-02 21:35 UTC, merged

2023-01-04 20:07 UTC, paulinhovba commented
A variável {{saudacao}} vem de onde no sistema?

2023-01-06 03:34 UTC, maxivane commented
> A variável {{saudacao}} vem de onde no sistema?

Essa variável {{saudacao}} utiliza esses parâmetros abaixo, de acordo com o horário que esta sendo enviando a mensagem será bom dia, boa tarde e assim por diante...
```
if (hh >= 6 && hh <= 11) {
    greeting = "Bom dia";
  } else if (hh > 11 && hh <= 17) {
    greeting = "Boa tarde";
  } else if (hh > 17 && hh <= 23) {
    greeting = "Boa noite";
  } else {
    greeting = "Boa madrugada";
  }
```

2023-01-06 12:02 UTC, paulinhovba commented
Opa, perfeito! Muito obrigado. Estaria na hora de fazer uma boa documentação né? Me diz, preciso fazer algumas customizações, vc se interessa? Whatsapp 54 99253 4085 Paulo

2023-12-14 03:03 UTC, ldurans commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/ldurans/izing.open.io/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: